##################################################
# +--------------------------------------------+ #
# |                   [mcRP]                   | #
# +--------------------------------------------+ #
##################################################
######==============IMPORTANT==============#######
##### Remember to back up your configuration #####
#####    DO NOT CHANGE THE VERSION NUMBER    #####
##################################################
Version: 1.3.1
Beta: 2
# Copyright 2013-2014 Licence LinCraft(?)
# http://dev.bukkit.org/licenses/2049-lin-craft-license/ 

# Welcome Message is enabled by default
Motd:
  Enabled: true
  Message: /mcrp motd set <message> to change your message

# UpdateCheck to check for updates
# AutoUpdate to down the updates
# These options do not depend on each other. So if Update check is off but AutoUpdate is on, the file will download
UpdateCheck: true
AutoUpdate: true
# Collects data and sends it to http://mcstats.org/plugin/mcRP
# Set to no if you dont want to send info
Metrics: true 
# Enable debugging?
Debug: false
  
##################################################
# +--------------------------------------------+ #
# |                  Realism                   | #
# +--------------------------------------------+ #
##################################################
# All Realism Configuration are bellow
Realism:
  # Set to false to disable all Realism
  Enabled: true
  # When players health bar is left with 3 hearts, the player will bleed out
  BleedMode: true
  # Allows player to destroy whole tree when log is cut with an axe
  TreeDestroy: true
  # Random chance of geting Diseases, to be cured you need to find an antidote to the set potion effect
  Diseases: 
    # Set to false to disable all Diseases
    Enabled: true
    Dehydration:
      Enabled: true
      # Chances out of 100 of geting infected. Format: Percentage
      InfectChance: 5
      # How long should it take before Diseases are given out again. Format: Seconds
      InfectTime: 600

##################################################
# +--------------------------------------------+ #
# |                   Skills                   | #
# +--------------------------------------------+ #
##################################################
# All skills configuration are listed bellow, default cooldown for all skills is 60 seconds
# Default duration for passive skills are 10 seconds
# Permissions are documented on the plugin page
# http://dev.bukkit.org/bukkit-plugins/mcrp/
Skills:
  Bless:
    # How long till player is allowed to use skill again. Format: Seconds
    Cooldown: 60
    # How long the potion effect of the skill will last for. Format: Seconds
    Duration: 10
  Confuse:
    Cooldown: 60
    # How long the potion effect of the skill will last for. Format: Seconds
    Duruation: 10
  Gills:
    Cooldown: 60
    Duration: 10
  MartyBoom:
    Cooldown: 60
  Might:
    Cooldown: 60
    Duration: 10
  Stealth:
    Cooldown: 60
    Duration: 10
  SuperJump:
    Cooldown: 60
    Duration: 10
  SuperPunch:
    Cooldown: 60    
  SuperSpeed:
    Cooldown: 60
    Durruation: 10
    
##################################################
# +--------------------------------------------+ #
# |                   Classes                  | #
# +--------------------------------------------+ #
##################################################
# All classes configuration are listed bellow, default cooldown for all skills is 60 seconds
# Default duration for passive skills are 10 seconds
# Permissions are documented on the plugin page
# http://dev.bukkit.org/bukkit-plugins/mcrp/
Classes:
  Bowman:
    Knockback:
      Cooldown: 60
      Damage: 2
      KnockbackRange: 2 
      Radius: 3
  Warrior:
    IronWill:
      Cooldown: 60
      Duruation: 10
    MonsterMagnet:
      Cooldown: 60
      Duruation: 10
      # The block radius at which all hostile mobs will be attracted to player when skill is used
      Radius: 10
    PowerSlash:
      Cooldown: 60
      Damage: 5
      # Maximum amount of mobs hit by this skill
      MaxMobHit: 3
      # Does this move only damage mosters or any mob in general
      MonstersOnly: false
      Radius: 3
# Setting allow legacy to true allows the use of mcrp v1.3.1 skills
# This setting comes into effect after players choose a class
# This setting does not effect players which do not have a class
# They are skill allowed to use legacy skills
AllowLegacy: true

##################################################
# +--------------------------------------------+ #
# |                  Database                  | #
# +--------------------------------------------+ #
##################################################
# All database information is stored bellow
# Storage options avalible are 'sqlite' and 'mysql' 
# NOTE: these are case insensitive
# By default Storage type is 'sqlite' so you dont have to edit the Info
# Info is only if Storage type is 'mysql'
# If you are using a server host, they should provide this info for you
Storage:
  Type: sqlite
  Info:
    Host: localhost
    Port: 3306
    Db: ''
    User: ''
    Pass: ''
    TablePrefix: 'mcrp_'
#======================[End]=====================#