############################################################
# +------------------------------------------------------+ #
# |                        mcRP                          | #
# +------------------------------------------------------+ #
############################################################
# This is config made by jackli213
# This Config was made funtional on the 20/08/12

ServerName: 

WelcomeMessage: Welcome to the server